version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ./uploads:/app/uploads 
      - .:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  db-data:
